### ISSUE TITLE
Game crash at launch factorio 0.18.34

### ISSUE THREAD

**Issue by UfaiX04** [Dysoch/DyWorld#348]
![error](https://user-images.githubusercontent.com/64732224/85945662-a2956780-b93f-11ea-862b-6452cffad921.png)

sorry for the image and not the log, i dont know how to get it and only screenshotted what came out at the launch

**Comment by DurchlauchtheitFreddy** [comment]
i had the same error, here's my log: (some other mods were loaded too, but the game crashed because of Dyworld)

   0.003 2020-06-29 10:39:19; Factorio 0.18.26 (build 51686, win64, steam)
   0.004 Operating system: Windows 10 (version 1903) 
   0.004 Program arguments: "C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64\Factorio.exe" 
   0.004 Read data path: C:/Program Files (x86)/Steam/steamapps/common/Factorio/data
   0.004 Write data path: C:/Users/Freddy/AppData/Roaming/Factorio [43208/237376MB]
   0.004 Binaries path: C:/Program Files (x86)/Steam/steamapps/common/Factorio/bin
   0.036 System info: [CPU: AMD Ryzen 5 1400 Quad-Core Processor, 8 cores, RAM: 7647/16317 MB, page: 11021/29629 MB, virtual: 4326/134217727 MB, extended virtual: 0 MB]
   0.036 Display options: [FullScreen: 1] [VSync: 1] [UIScale: automatic (100.0%)] [Native DPI: 1] [Screen: 255] [Special: lmw] [Lang: en]
   0.059 Available displays: 2
   0.060  [0]: \\.\DISPLAY1 - NVIDIA GeForce GTX 1060 6GB {0x05, [0,0], 1920x1080, 32bit, 60Hz}
   0.061  [1]: \\.\DISPLAY2 - NVIDIA GeForce GTX 1060 6GB {0x01, [1920,0], 1920x1080, 32bit, 60Hz}
   0.186 [Direct3D11] Display: 0, Output: 0, DisplayAdapter: 0, RenderingAdapter: 0; d3dcompiler_47.dll
   0.432 Initialised Direct3D[0]: NVIDIA GeForce GTX 1060 6GB; id: 10de-1c03; driver: nvldumdx.dll 26.21.14.3200
   0.432   D3D Feature Level: 11.1, DXGI 1.5+, SwapChain: 3,flip-discard,-,-,-,none
   0.432   [Local Video Memory] Budget: 5144MB, CurrentUsage: 2MB, Reservation: 0/2723MB
   0.432   [Non-Local Vid.Mem.] Budget: 7342MB, CurrentUsage: 0MB, Reservation: 0/3875MB
   0.432   Tiled resources: Tier 2
   0.432   Unified Memory Architecture: No
   0.432   BGR 565 Supported: Yes
   0.432   MaximumFrameLatency: 3, GPUThreadPriority: 0
   0.432 Graphics settings preset: very-high
   0.432   Dedicated video memory size 6052 MB
   0.504 Desktop composition is active.
   0.504 Graphics options: [Graphics quality: high] [Video memory usage: all] [Light scale: 100%] [DXT: high-quality] [Color: 32bit]
   0.504                   [Max threads (load/render): 32/8] [Max texture size: 0] [Tex.Stream.: 0] [Rotation quality: normal] [Other: STDC] [B:0,C:0,S:100]
   0.605 DSound: Starting _dsound_update thread
   0.606 DSound: Enter _dsound_update; tid=1968
   0.982 Info ModManager.cpp:253: Found duplicate mod aai-industry, using higher version (0.4.12 > 0.4.11).
   1.205 Info ModManager.cpp:253: Found duplicate mod bobassembly, using higher version (0.18.5 > 0.18.4).
   1.213 Info ModManager.cpp:253: Found duplicate mod bobenemies, using higher version (0.18.5 > 0.18.4).
   1.260 Info ModManager.cpp:253: Found duplicate mod bobmodules, using higher version (0.18.3 > 0.18.2).
   1.281 Info ModManager.cpp:253: Found duplicate mod bobplates, using higher version (0.18.8 > 0.18.7).
   1.294 Info ModManager.cpp:253: Found duplicate mod bobpower, using higher version (0.18.6 > 0.18.5).
   1.300 Info ModManager.cpp:253: Found duplicate mod bobrevamp, using higher version (0.18.5 > 0.18.4).
   1.324 Info ModManager.cpp:253: Found duplicate mod bobwarfare, using higher version (0.18.6 > 0.18.5).
   1.401 Info ModManager.cpp:253: Found duplicate mod MaxRateCalculator, using higher version (3.3.36 > 3.2.35).
   1.450 Info ModManager.cpp:253: Found duplicate mod ScienceCostTweakerM, using higher version (0.18.1 > 0.18.0).
   1.467 Info ModManager.cpp:253: Found duplicate mod SmartTrains, using higher version (5.0.2 > 5.0.1).
   1.524 Info ModManager.cpp:253: Found duplicate mod stdlib, using higher version (1.4.3 > 1.4.2).
   1.560 Info ModManager.cpp:253: Found duplicate mod VehicleSnap, using higher version (1.18.3 > 1.18.2).
   1.577 Info ModManager.cpp:253: Found duplicate mod VehicleWagon2, using higher version (2.18.4 > 2.18.2).
   1.589 Loading mod settings dangOreus 1.5.17 (settings.lua)
   1.590 Loading mod settings DyWorld 0.9.7 (settings.lua)
   1.590 Loading mod settings Factorissimo2 2.4.2 (settings.lua)
   1.590 Loading mod settings miniloader 1.11.1 (settings.lua)
   1.591 Loading mod settings nixie-tubes 0.18.3 (settings.lua)
   1.591 Loading mod settings Squeak Through 1.8.0 (settings.lua)
   1.591 Loading mod settings Warehousing 0.3.0 (settings.lua)
   1.607 Loading mod core 0.0.0 (data.lua)
   1.805 Loading mod base 0.18.26 (data.lua)
   2.609 Loading mod DyWorld 0.9.7 (data.lua)
   2.636 Error ModManager.cpp:1508: Failed to load mod "DyWorld": __DyWorld__/data.lua:4: __DyWorld__/data/core/data.lua:50: __DyWorld__/data/core/edits/item-group-change.lua:86: attempt to index field 'compilatron-chest' (a nil value)
stack traceback:
	__DyWorld__/data/core/edits/item-group-change.lua:86: in main chunk
	[C]: in function 'require'
	__DyWorld__/data/core/data.lua:50: in main chunk
	[C]: in function 'require'
	__DyWorld__/data.lua:4: in main chunk
stack traceback:
	[C]: in function 'require'
	__DyWorld__/data/core/data.lua:50: in main chunk
	[C]: in function 'require'
	__DyWorld__/data.lua:4: in main chunk
stack traceback:
	[C]: in function 'require'
	__DyWorld__/data.lua:4: in main chunk
   2.638 Loading mod core 0.0.0 (data.lua)
   2.780 Checksum for core: 1234716632
   2.951 Error ModManager.cpp:1508: Error in assignID: recipe-category with name 'crafting' does not exist.

Source: default (utility-sprites).
   3.046 Initial atlas bitmap size is 16384
   3.046 Created atlas bitmap 2048x544 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
   3.059 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
   3.142 Parallel Sprite Loader initialized (threads: 7)
   3.441 Sprites loaded
   3.464 Generated mipmaps (5) for atlas [0] of size 2048x544   
   3.464 Custom mipmaps uploaded.
   3.471 Factorio initialised
   3.478 Mods to disable:Failed to load mods: __DyWorld__/data.lua:4: __DyWorld__/data/core/data.lua:50: __DyWorld__/data/core/edits/item-group-change.lua:86: attempt to index field 'compilatron-chest' (a nil value)
stack traceback:
	__DyWorld__/data/core/edits/item-group-change.lua:86: in main chunk
	[C]: in function 'require'
	__DyWorld__/data/core/data.lua:50: in main chunk
	[C]: in function 'require'
	__DyWorld__/data.lua:4: in main chunk
stack traceback:
	[C]: in function 'require'
	__DyWorld__/data/core/data.lua:50: in main chunk
	[C]: in function 'require'
	__DyWorld__/data.lua:4: in main chunk
stack traceback:
	[C]: in function 'require'
	__DyWorld__/data.lua:4: in main chunk

Mods to be disabled:
• DyWorld (0.9.7)

**Comment by jenheilemann** [comment]
Also seeing this crash in 1.0. Dyworld is the only mod loaded.

**Comment by chris-hexx** [comment]
I'm also seeing this with 1.0 and only Dyworld activated.
